FROM ubuntu:24.04

ARG REALSENSE_ROS_TAG=4.57.2
ARG LIBREALSENSE_TAG=v2.57.2
ARG DISTRO=jazzy

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    lsb-release \
    pkg-config \
    git \
    cmake \
    build-essential \
    python3-pip \
    libssl-dev \
    libusb-1.0-0-dev \
    libgtk-3-dev \
    libglfw3-dev \
    libeigen3-dev \
    netcat-traditional \
    ntpdate \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN apt-get update && apt-get install -y \
    ros-${DISTRO}-ros-base \
    ros-${DISTRO}-demo-nodes-cpp \
    ros-${DISTRO}-rmw-zenoh-cpp \
    ros-dev-tools \
    python3-rosdep \
    python3-smbus \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root/ros2_ws
COPY ./src ./src

WORKDIR /
RUN git clone --depth 1 --branch ${LIBREALSENSE_TAG} https://github.com/IntelRealSense/librealsense.git
WORKDIR /librealsense
RUN mkdir build && cd build && \
    cmake ../ \
        -DBUILD_EXAMPLES=false \
        -DBUILD_GRAPHICAL_EXAMPLES=false \
        -DCMAKE_BUILD_TYPE=Release && \
    make -j$(nproc) && \
    make install
RUN rm -rf /librealsense

RUN apt-get update && apt-get install -y \
    ros-${DISTRO}-realsense2-camera \
    ros-${DISTRO}-realsense2-description \
    && apt-get clean

WORKDIR /root/ros2_ws

RUN git clone https://github.com/IntelRealSense/realsense-ros.git -b ${REALSENSE_ROS_TAG} src/realsense-ros

RUN . /opt/ros/${DISTRO}/setup.sh && \ 
    rosdep init && rosdep update && \
    rosdep install -i --from-path src --rosdistro ${DISTRO} -y

RUN sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen

WORKDIR /root/ros2_ws

RUN echo "source /opt/ros/${DISTRO}/setup.bash" >> ~/.bashrc
RUN echo "alias control-hexapod='colcon build && source install/setup.bash && (fastdds discovery -i 0 &) && ros2 launch control robot_launch.py'" >> ~/.bashrc



# CMD ["/bin/bash", "-c", "ntpdate pool.ntp.org && source /opt/ros/jazzy/setup.bash && colcon build && source install/setup.bash && (fastdds discovery -i 0 &) && ros2 launch pi_control robot_launch.py"]