# docker/Dockerfile.wsl

FROM ros:jazzy-ros-base

SHELL ["/bin/bash", "-c"]

ARG DISTRO=jazzy
ENV DEBIAN_FRONTEND=noninteractive

# Install core and GUI tool dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    pipx \
    git \
    python3-pip \
    python3-opencv \
    python3-pyqt5 \
    python3-yaml \
    iputils-ping \
    iproute2 \
    curl \
    lsb-release \
    gnupg \
    && apt-get clean

# Install ROS tools and Zenoh RMW
RUN apt-get update && apt-get install -y \
    ros-${DISTRO}-cv-bridge \
    ros-${DISTRO}-plotjuggler \
    ros-${DISTRO}-plotjuggler-ros \
    ros-${DISTRO}-joint-state-publisher \
    ros-${DISTRO}-joint-state-publisher-gui \
    ros-${DISTRO}-teleop-twist-joy \
    ros-${DISTRO}-joy \
    ros-${DISTRO}-xacro \
    ros-${DISTRO}-rmw-zenoh-cpp \
    && rm -rf /var/lib/apt/lists/*

# Set up ROS 2 workspace
WORKDIR /root/ros2_ws
COPY ./src ./src

# Source ROS environment and add aliases
RUN echo "source /opt/ros/${DISTRO}/setup.bash" >> ~/.bashrc
RUN echo "alias command-hexapod='colcon build && source install/setup.bash && ros2 launch command command.launch.py'" >> ~/.bashrc